---
title: "ENVS-193DS_seed-counts"
format: 
  html:
    toc: true
    toc-location: left
    code-fold: true
    theme: yeti
editor: visual
execute: 
  message: false
  warning: false
editor: visual
editor: visual
---

## Seed Counts

# Introduction

testing

# Methods

```{r}
# should haves
library(tidyverse)
library(here)
library(janitor)
library(ggeffects)
library(performance)
library(naniar)
library(skimr)
library(flextable)
library(car)
library(broom)
library(corrplot)
library(AICcmodavg)
library(GGally)
# would be nice to have
library(MuMIn)
library(DHARMa)
#library(equatiomatic)
library(corrplot)
library(MASS) # have to read this in before tidyverse 
library(lme4)
library(glmmTMB)
```

```{r}
seed_count <- read_csv(here("data", "shrubstudy_seed_ctwt.ms.data.csv")) %>% 
  # make the column names cleaner
  clean_names()
```

```{r}
ggplot(seed_count, aes(x = nr_seeds)) +
  geom_histogram(bins = 17)
```

```{r}
seed_count %>% 
  select(!species) %>% 
  ggpairs()
```

```{r}
skim(seed_count)
```

## Building Models

```{r}
# linear model, we know this is wrong
seedmod1 <- lm(nr_seeds ~ treatment + species + total_nr_infl, data = seed_count)

# generalized linear model with Poisson distribution
seedmod2 <- glm(nr_seeds ~ treatment + species + total_nr_infl, data = seed_count, family = "poisson")
seedmod2.a <- glm(nr_seeds ~ treatment + species + total_nr_infl, data = seed_count, family = "poisson")

# generalized linear model with negative binomial distribution
seedmod3 <- glm.nb(nr_seeds ~ treatment + species + total_nr_infl, data = seed_count)
seedmod3.a <- glmmTMB(nr_seeds ~ treatment + species + total_nr_infl, data = seed_count, family = "nbinom2")

# generalized linear model with Poisson distribution and random effect of site
seedmod4 <- glmer(nr_seeds ~ species + total_nr_infl + (1|treatment), data = seed_count, family = "poisson")
seedmod4.a <- glmmTMB(nr_seeds ~ species + total_nr_infl + (1|treatment), data = seed_count, family = "poisson")

# generalized linear model with negative binomial distribution and random effect of site
seedmod5 <- glmer.nb(nr_seeds ~ species + total_nr_infl + (1|treatment), data = seed_count)
seedmod5.a <- glmmTMB(nr_seeds ~ species + total_nr_infl + (1|treatment), data = seed_count, family = "nbinom2")
```

```{r}
# check diagnostics
plot(simulateResiduals(seedmod1)) # bad

plot(simulateResiduals(seedmod2)) # bad

plot(simulateResiduals(seedmod3)) # ok?

plot(simulateResiduals(seedmod4)) # bad

plot(simulateResiduals(seedmod5)) # bad/ok?
```

```{r}
MuMIn::model.sel(seedmod1, seedmod2, seedmod3, seedmod4, seedmod5)
```

```{r}
seedmod3
```

```{r}
summary(seedmod3)
```

```{r}
confint(seedmod3)
```

```{r}
# adjusted R2
r.squaredGLMM(seedmod3)
```

```{r}
# model object in table
seedmod3 %>% 
  as_flextable()
```

# Results

# Works Cited
